### ISSUE TITLE
ian-terraform 초기 밑작업

### ISSUE THREAD

**Issue by smileostrich** [smileostrich/ian-works#1]
**Todo List**

- [x] Terraform Clould for 2FA, ~/.terraformrc 세팅
- [x] AWS IAM 관리(MFA, role, policy 등) (AWS IAM issue 참조)
- [x] AWS 루트계정 액세스키 없애기
- [ ] AWS 테라폼 밑작업
- [x] S3 and dynamodb for lock
