### ISSUE TITLE
AWS IAM 세팅

### ISSUE THREAD

**Issue by smileostrich** [smileostrich/ian-works#2]
# Todo List

- [ ]  AWS root 계정에 MFA
- [ ]  AWS IAM 계정들에 MFA force
- [ ]  AWS IAM role 생성
- [ ]  AWS IAM 유저그룹 생성

# 기타 참고
- AWS EC2 Instance Connect 사용하도록
